# Site settings
title: Gill Thorpe
email: info@gillthorpe.com
description:
  Gill Thorpe Textile design and Visual Communication
baseurl: ""
url: "http://gillthorpe.com" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown
