# Site settings
title: Gill Thorpe
email: info@gillthorpe.com
description:
  Gill Thorpe Textile design and Visual Communication
baseurl: ""
url: "gill-thorpe.github.io"
twitter_username:

# Build settings
markdown: kramdown
